### ISSUE TITLE
Shouldn't this repo be called "Mr. Boom"? (the name of the icon assets)

### ISSUE THREAD

**Issue by alfrix** [libretro-thumbnails/MrBoom#2]
Currently Mr. Boom is a "content-less core" which means it doesn't create it's playlist; so this thumbs and even the icon assets are useless unless you create a playlist manually with this style:
```
.\cores\mrboom_libretro.dll
Mr.Boom
.\cores\mrboom_libretro.dll
DETECT
DETECT
Mr. Boom.lpl
```
Even then you have the problem that the thumbnail repo should have the same name as the assets.

Mr.[space]Boom

EDIT: so here should be MR._Boom

**Comment by RobLoach** [comment]
We could add a mock Mr Boom file to the DB so that the scanner works and the playlist pop up.

**Comment by alfrix** [comment]
I'm not certain in what you are asking, my thoughts are this:

The asset is called Mr. Boom
https://github.com/libretro/retroarch-assets/blob/master/xmb/monochrome/png/Mr.%20Boom.png

So the thumbnail folder should have the same name. 

Which brings me to this repository name, which should be Mr._Boom

**Comment by RobLoach** [comment]
`Mr.Boom` is the core name (no space).....

![mr boom](https://user-images.githubusercontent.com/25086/33862051-da6da78a-deae-11e7-8f7f-4f76bebc4eec.png)

Made two PRs to allow it to show in the playlists: https://github.com/libretro/libretro-super/pull/639 https://github.com/libretro/libretro-database/pull/552

We could add other files to the DAT to ease scanning.

**Comment by alfrix** [comment]
> Mr.Boom is the core name (no space).....

So you want to also change the asset name then. 
I didn't want to do that because everytime you change an asset name, the old one remain in the users computer. it's not relevant i suppose.

**Comment by RobLoach** [comment]
Updated to `MrBoom`, since the `.` breaks playlist things. Should be fixed once RDBs are updated.
